In [1]:
(5, 7)

(5, 7)

In [2]:
5, 7

(5, 7)

In [7]:
# 單一個要加 ","
(5, )

(5,)

In [8]:
list_a = [1, 3, 5, 7, 9]
list_b = [3, 5, 6, 7, 9]
list_a + list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [10]:
import numpy as np
array_a = np.array([1, 3, 5, 7, 9])
array_b = np.array([3, 5, 6, 7, 9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [14]:
import numpy as np

l = [[1, 2, 3],[2, 3, 4]]
array = np.array(l)
array.ndim, array.shape, array.size, array.dtype

(2, (2, 3), 6, dtype('int64'))

In [17]:
import numpy as np
np.random.randn(10,5)

array([[-0.2115755 ,  1.43236187,  2.306911  ,  1.19424404, -1.75927173],
       [ 1.38084583,  0.03120367,  1.20275879,  0.97092019,  0.07603791],
       [ 0.67195082, -0.94720042, -0.34977296,  2.49692855,  0.24146176],
       [-0.64244429,  1.18842381,  0.26194255, -1.15821728,  0.09974325],
       [-0.11746087, -0.44958544,  0.17819431,  0.48588699,  0.73923177],
       [-0.4312601 ,  1.61480727,  0.13945506, -0.52999808, -0.66184052],
       [-0.62884286, -0.45110408,  0.75600054, -0.43180134,  0.86890168],
       [-0.17506262, -0.79246808, -0.48776677,  2.18028884, -0.24490554],
       [ 0.10699444,  1.1880349 ,  0.36325022, -0.92692486, -0.30586825],
       [-0.18398966,  1.37190189, -0.52850888,  1.00170961, -0.77271614]])

In [21]:
# 50個學生，每個學生有5個分數(50-100)
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 79,  86,  71,  82,  66],
       [ 94,  71,  72, 100,  80],
       [ 94,  99,  53,  57,  66],
       [ 74,  86,  98,  80,  98],
       [ 75,  89,  65,  50,  67],
       [ 62,  91,  81,  98,  85],
       [ 60,  93,  57,  88,  67],
       [ 64,  88,  90,  58,  88],
       [ 62,  70,  87,  76,  88],
       [ 52,  84,  65,  83,  80],
       [ 55,  90,  50,  69,  57],
       [ 58,  57,  87,  90,  81],
       [ 90,  78,  69,  84,  75],
       [ 72,  70, 100,  97,  94],
       [ 53, 100,  93,  79,  94],
       [ 81,  73,  59,  83,  89],
       [ 98,  99,  72,  84,  60],
       [ 78,  53,  53,  95,  91],
       [ 77,  88,  58,  84,  97],
       [ 91,  90,  95,  54,  75],
       [ 79,  72,  57,  90,  56],
       [ 97,  57,  82,  95,  54],
       [ 56,  66,  71,  99,  77],
       [ 50,  74,  77,  59,  81],
       [ 69, 100,  59,  91,  77],
       [ 54,  88,  67,  50,  80],
       [ 79,  90,  92,  98,  62],
       [ 59,  86,  84,  91,  59],
       [ 98,  60,  89,  96,  68],
       [ 89,  