In [1]:
(5, 7)

(5, 7)

In [2]:
5, 7

(5, 7)

In [7]:
# 單一個要加 ","
(5, )

(5,)

In [8]:
list_a = [1, 3, 5, 7, 9]
list_b = [3, 5, 6, 7, 9]
list_a + list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [10]:
import numpy as np
array_a = np.array([1, 3, 5, 7, 9])
array_b = np.array([3, 5, 6, 7, 9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [14]:
import numpy as np

l = [[1, 2, 3],[2, 3, 4]]
array = np.array(l)
array.ndim, array.shape, array.size, array.dtype

(2, (2, 3), 6, dtype('int64'))

In [17]:
import numpy as np
np.random.randn(10,5)

array([[-0.2115755 ,  1.43236187,  2.306911  ,  1.19424404, -1.75927173],
       [ 1.38084583,  0.03120367,  1.20275879,  0.97092019,  0.07603791],
       [ 0.67195082, -0.94720042, -0.34977296,  2.49692855,  0.24146176],
       [-0.64244429,  1.18842381,  0.26194255, -1.15821728,  0.09974325],
       [-0.11746087, -0.44958544,  0.17819431,  0.48588699,  0.73923177],
       [-0.4312601 ,  1.61480727,  0.13945506, -0.52999808, -0.66184052],
       [-0.62884286, -0.45110408,  0.75600054, -0.43180134,  0.86890168],
       [-0.17506262, -0.79246808, -0.48776677,  2.18028884, -0.24490554],
       [ 0.10699444,  1.1880349 ,  0.36325022, -0.92692486, -0.30586825],
       [-0.18398966,  1.37190189, -0.52850888,  1.00170961, -0.77271614]])

In [22]:
# 50個學生，每個學生有5個分數(50-100)
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 92,  89,  70,  93,  65],
       [ 52,  87,  87,  86,  98],
       [ 56,  87,  52,  87,  68],
       [ 81,  58,  69,  86,  58],
       [ 67,  82, 100,  83,  95],
       [ 65,  69,  89,  90,  92],
       [ 93,  87,  76,  50,  84],
       [ 62,  74,  96,  65,  66],
       [ 50,  70,  75,  87,  68],
       [ 98,  92,  67,  53,  70],
       [ 56,  62, 100,  94,  83],
       [ 90,  88,  77,  75,  74],
       [ 76,  57,  96,  80,  59],
       [ 59,  50,  96, 100,  61],
       [ 57,  82,  71,  86,  71],
       [ 80,  77,  64,  73,  78],
       [ 53,  53, 100,  69,  95],
       [ 89,  54,  97, 100,  86],
       [ 99,  59,  51,  88,  94],
       [ 88,  61,  88,  96,  50],
       [ 51,  66,  73,  54,  93],
       [ 81,  92,  61,  89,  92],
       [ 50,  93,  97,  84,  74],
       [ 62,  65,  97,  69,  55],
       [ 77, 100,  60,  80,  87],
       [ 52,  98,  54,  80,  98],
       [ 69,  70, 100,  73,  59],
       [ 63,  96,  56,  88,  92],
       [ 86,  92,  67,  62,  63],
       [ 86,  

In [23]:
# 第一個學生
scores[0, :]
# 前五個學生
scores[:5, :]
# 最後五個學生
scores[-5:, :]

array([[89, 58, 84, 75, 90],
       [69, 64, 51, 98, 81],
       [91, 83, 83, 98, 85],
       [53, 91, 72, 86, 56],
       [68, 59, 58, 65, 98]])

In [24]:
# 全班第一科的分數
scores[:, 0]

array([92, 52, 56, 81, 67, 65, 93, 62, 50, 98, 56, 90, 76, 59, 57, 80, 53,
       89, 99, 88, 51, 81, 50, 62, 77, 52, 69, 63, 86, 86, 74, 91, 57, 53,
       61, 65, 91, 65, 99, 51, 78, 91, 51, 97, 61, 89, 69, 91, 53, 68])

In [25]:
# 全班第二科的分數
scores[:, 1]

array([ 89,  87,  87,  58,  82,  69,  87,  74,  70,  92,  62,  88,  57,
        50,  82,  77,  53,  54,  59,  61,  66,  92,  93,  65, 100,  98,
        70,  96,  92,  63,  87,  70,  58,  90,  89,  72,  51,  59,  84,
        52,  98,  96,  90,  75,  69,  58,  64,  83,  91,  59])

In [27]:
# 每位學生的總分
total = scores[:, 0] + scores[:, 1] + scores[:, 2] + scores[:, 3] + scores[:, 4]
total

array([409, 410, 350, 352, 427, 405, 390, 363, 350, 380, 395, 404, 368,
       366, 367, 372, 370, 426, 391, 383, 337, 415, 398, 348, 404, 382,
       371, 395, 370, 371, 393, 351, 278, 372, 390, 368, 323, 381, 389,
       302, 422, 418, 362, 415, 346, 396, 363, 440, 358, 348])